### PR TITLE
Aurora Palace hotfix

### LINKED ISSUE #71: Rooms in Aurora Palace generate improperly
Forge Version: 13.20.0.2315
Twilight Forest Version: 2.4.0.27

Rooms where wooden planks and slabs generate in an abnormal fashion

### LINKED ISSUE #496: Overhaul Aurora Palace
What I expected to happen:

Rooms generate properly, possible to navigate through the tower without missing stairways, blocked doors, etc.

What happened instead:

Some rooms generate badly

### LINKED ISSUE #2137: [Bug] Ice Queen room sometimes doesn't spawn
### NeoForge Version

1.20.6

### Twilight Forest Version

twilightforest-1.20.6-4.5.2490-universal

### Client Log

_No response_

### Crash Report (if applicable)

_No response_

### Steps to Reproduce

1) Create a world with the seed -5854469041862538378
2) Enter the Twilight Forest
3) Teleport to 5610 36 3599
4) Observe that the palace has no Ice Queen

### What You Expected

All ice palaces have Ice Queen rooms

### What Happened Instead

Certain ice palaces fail to generate Ice Queen rooms

### Additional Details

~

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

### PR DESCRIPTION
**Pull request by Sleepy-Horse**
This PR fixes most issues with Aurora Palace; however, it is still hardcoded. It fixes:
- Covered bridge and entrance
- Beard and roof intersection with wings
- Guaranteeing Ice Queen spawning
- Unreachable or impassable floors
- Incorrectly rotated chests
- Incorrectly rotated stairs to the entrance wing

It adds:
- A new anchor system to avoid intersections between floors
- A new parkour floor

It changes some floor types for better generation.

Fix #2137
Fix #496
Fix #71

Some screenshots for demonstration:
image
image
image
image
image

### CODE REVIEW

File: src/main/java/twilightforest/util/WorldUtil.java [hunk 1]
```diff
@@ -62,6 +63,23 @@ public static BlockPos randomOffset(RandomSource random, BlockPos pos, int rx, i
...
+		int totalWeight = list.stream().mapToInt(Pair::getSecond).sum();
+		int randomValue = rng.nextInt(totalWeight);
+
+		for (Pair<T, Integer> pair : list) {
+			randomValue -= pair.getSecond();
+			if (randomValue < 0) {
+				return pair.getFirst();
+			}
+		}
+		return list.get(rng.nextInt(list.size())).getFirst(); // This line should never be reached if input list is valid
```
Comment (Tamaized) [inline src/main/java/twilightforest/util/WorldUtil.java]: can this be replaced with `return getRandomElement(list, rng).getFirst()` to reduce duplicate code?

**Comment by Tamaized** [comment]
I feel like there's a better way to do the FloorWith3x3Map stuff, but I'm not going to fret about it since this is all going to eventually become NBT.

**Review by Tamaized — APPROVED** [review]
