### PR TITLE
Fix drying rack item disapearing

### LINKED ISSUE #2521: Drying rack Eat your item upon being destroyed
### NeoForge Version

21.1.217

### Twilight Forest Version

4.8.3260

### Client Log

_No response_

### Crash Report (if applicable)

_No response_

### Steps to Reproduce

1.Put item on the rack
2.Break it
3.Observe that only the rack are drop and items on it are gone
(optional) cry for your item is gone

### What You Expected

both the rack and item to drop

### What Happened Instead

only the rack are drop suggesting the item are sent to shadow realm

### Additional Details

found it by complete accident while trying to loot campsite

### Please Read and Confirm The Following

- [x] I have confirmed this bug can be replicated without the use of Optifine.
- [x] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [x] I have confirmed this issue is unique and has not been reported already.

### PR DESCRIPTION
**Pull request by Fywchis**
Fix #2521

Changed function that drops item.

After fix:

https://github.com/user-attachments/assets/321a490e-c160-4e80-9e9c-17356c8b16af

### CODE REVIEW

File: src/main/java/twilightforest/block/DryingRackBlock.java [hunk 1]
```diff
@@ -116,7 +116,13 @@ public void animateTick(BlockState state, Level level, BlockPos pos, RandomSourc
 
 	@Override
 	protected void onRemove(BlockState state, Level level, BlockPos pos, BlockState newState, boolean movedByPiston) {
-		Containers.dropContentsOnDestroy(state, newState, level, pos);
+		double x = pos.getX();
+		double y = pos.getY();
+		double z = pos.getZ();
+		BlockEntity blockEntity = level.getBlockEntity(pos);
+		if (!(blockEntity instanceof DryingRackBlockEntity)) {return;}
```
Comment (Tamaized) [inline src/main/java/twilightforest/block/DryingRackBlock.java]: I'm not a fan of this kind of formatting, I prefer:
```java
if (!(blockEntity instanceof DryingRackBlockEntity dryingRackBlockEntity))
    return;
 ItemStack item = dryingRackBlockEntity.takeTheItem();
 ```

Comment (Tamaized) [reply src/main/java/twilightforest/block/DryingRackBlock.java]: Also the `dryingRackBlockEntity.takeTheItem()` can just be inlined into Containers.dropItemStack at that point
