### PR TITLE
Druid hut chests

### LINKED ISSUE #2265: Druit hut not generating loot
### NeoForge Version

21.1.42

### Twilight Forest Version

4.6.2780

### Client Log

_No response_

### Crash Report (if applicable)

_No response_

### Steps to Reproduce

Visit druid hut
Druid spawners and structure itself is generated without issues
Chests that should contain loot are empty

### What You Expected

Usual loot table with food and useful early game stuff

### What Happened Instead

3 empty chests without any loot

### Additional Details

Another player found a druid hut that had loot, but only in 1/3 of the chests.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

### PR DESCRIPTION
**Pull request by Sleepy-Horse**
Fix #2265
Fix a bug where using `/place feature twilightforest:druid_hut` placed blocks only on the server side.

### CODE REVIEW

**Comment by Tamaized** [comment]
I think there's a constant class somewhere for these flags, if it exists we should probably replace the magic numbers with them.

File: src/main/java/twilightforest/world/components/feature/templates/DruidHutFeature.java [hunk 1]
```diff
@@ -53,7 +53,7 @@ protected void postPlacement(WorldGenLevel world, RandomSource random, Structure
 			config.buildAddProcessors(placementSettings, random);
 			placementSettings.addProcessor(CobbleVariants.INSTANCE).addProcessor(StoneBricksVariants.INSTANCE);
 
-			template.placeInWorld(world, placementPos, placementPos, placementSettings, random, 20);
+			template.placeInWorld(world, placementPos, placementPos, placementSettings, random, Block.UPDATE_CLIENTS);
```
Comment (Tamaized) [inline src/main/java/twilightforest/world/components/feature/templates/DruidHutFeature.java:56]: 20 looks to be UPDATE_KNOWN_SHAPE and UPDATE_INVISIBLE, are these still needed?

Comment (Sleepy-Horse) [reply src/main/java/twilightforest/world/components/feature/templates/DruidHutFeature.java:56]: Drullkus said it is fine to place without them if I think so.
[Proof](https://discord.com/channels/313006291012288521/384911556468801537/1290035483153535057)
