### PR TITLE
we can actually spawn the naga without crashing now

### LINKED ISSUE #7: NPE when attempting to spawn naga
java.lang.NullPointerException: Ticking block entity
    	at twilightforest.tileentity.TileEntityTFBossSpawner.spawnMyBoss(TileEntityTFBossSpawner.java:76)
    	at twilightforest.tileentity.TileEntityTFBossSpawner.update(TileEntityTFBossSpawner.java:54)
    	at net.minecraft.world.World.updateEntities(World.java:1952)
    	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:647)
    	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:784)
    	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:688)
    	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156)
    	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:537)
    	at java.lang.Thread.run(Thread.java:745)

### PR DESCRIPTION
**Pull request by Tamaized**
This is to close #7  
Things to note:
- Because fields are initialized AFTER the super in the constructor I had to initialize 'movementAI' within 'initEntityAI' and remove the 'final' (do we really need it though)
- 'getParts()' was also crashing because vanilla doesnt check for nulls, so I just did a copy of our 'body' array without the nulls.
- The segment render was really wonky, as in rotating in an odd jaggy way, I changed it to use 'rotationYaw' and 'rotationPitch' instead which seems pretty smooth to me. I left the old code commented out incase you guys wanted to revert and fix it if there's a proper way.
- Fixed which trophy drops, was the lich before.
- Stuff is still broken/needs work such as AI that I'll leave to you guys since well.. i'm not that great at it :P
- Rest of the changes all should have comments next to them. Feel free to change/expand upon this as I just wanted to make the naga spawnable.

### CODE REVIEW

**Comment by williewillus** [comment]
can you remove all your comments saying `// was <x>, now <y>`?
those kinds of notes belong in the commit messages and in this ticket.
months from now we won't care why it was broken, just that it works now. we can always do a `git blame` later to find this PR again.

File: src/main/java/twilightforest/client/renderer/entity/RenderTFNagaSegment.java [hunk 1]
```diff
@@ -29,10 +29,10 @@ public void renderMe(Entity par1Entity, double par2, double par4, double par6, f
     {
         GlStateManager.pushMatrix();
         GlStateManager.translate((float)par2, (float)par4, (float)par6);
-        GlStateManager.rotate(180 - MathHelper.wrapDegrees(par8), 0.0F, 1.0F, 0.0F);
+        GlStateManager.rotate(180 - MathHelper.wrapDegrees(par1Entity.rotationYaw), 0.0F, 1.0F, 0.0F); // Was par8 instead of par1Entity.rotationYaw
```
Comment (williewillus) [inline src/main/java/twilightforest/client/renderer/entity/RenderTFNagaSegment.java]: here

File: src/main/java/twilightforest/client/renderer/entity/RenderTFNagaSegment.java [hunk 2]
```diff
@@ -29,10 +29,10 @@ public void renderMe(Entity par1Entity, double par2, double par4, double par6, f
...
         
         // pitch
-        float pitch = par1Entity.prevRotationPitch + (par1Entity.rotationPitch - par1Entity.prevRotationPitch) * time;
+        float pitch = par1Entity.rotationPitch; // Was: par1Entity.prevRotationPitch + (par1Entity.rotationPitch - par1Entity.prevRotationPitch) * time;
```
Comment (williewillus) [inline src/main/java/twilightforest/client/renderer/entity/RenderTFNagaSegment.java]: and here

File: src/main/java/twilightforest/entity/boss/EntityTFNaga.java [hunk 3]
```diff
@@ -322,7 +332,7 @@ private void setSegmentsPerHealth()
 	{
 		int oldSegments = this.currentSegmentCount;
 		int newSegments = MathHelper.clamp((int) ((this.getHealth() / healthPerSegment) + (getHealth() > 0 ? 2 : 0)), 0, MAX_SEGMENTS);
-
+		this.currentSegmentCount = newSegments; // spawnBodySegments() was using the currentSegmentCount which happened to be set after the call, so the segments never actually spawned.
```
Comment (williewillus) [inline src/main/java/twilightforest/entity/boss/EntityTFNaga.java]: and here

File: src/main/java/twilightforest/entity/boss/EntityTFNaga.java [hunk 4]
```diff
@@ -650,16 +659,13 @@ private boolean isEntityWithinHomeArea(Entity entity)
...
 			{
-				if (body[i] == null || body[i].isDead)
-				{
-					body[i] = new EntityTFNagaSegment(this, i);
-					body[i].setLocationAndAngles(posX + 0.1 * i, posY + 0.5D, posZ + 0.1 * i, rand.nextFloat() * 360F, 0.0F);
-					world.spawnEntity(body[i]);
-				}
+				body[i] = new EntityTFNagaSegment(this, i);
+				body[i].setLocationAndAngles(posX + 0.1 * i, posY + 0.5D, posZ + 0.1 * i, rand.nextFloat() * 360F, 0.0F);
+				if (!world.isRemote) world.spawnEntity(body[i]); // Moved the !world.isRemote check here as the segments were not spawning on the client side otherwise for some reason.
```
Comment (williewillus) [inline src/main/java/twilightforest/entity/boss/EntityTFNaga.java]: and here (I don't like the sound of "for some reason"...can you dig into it more?)

File: src/main/java/twilightforest/entity/boss/EntityTFNaga.java [hunk 5]
```diff
@@ -777,6 +783,8 @@ public boolean attackEntityFromPart(EntityDragonPart entitydragonpart, DamageSou
     @Override
     public Entity[] getParts()
     {
-        return body;
+    	List<EntityTFNagaSegment> list = new ArrayList<EntityTFNagaSegment>(Arrays.asList(body));
+    	list.removeAll(Collections.singleton(null));
+    	return list.toArray(new EntityTFNagaSegment[list.size()]); // This cannot contain nulls
```
Comment (williewillus) [inline src/main/java/twilightforest/entity/boss/EntityTFNaga.java]: try something like `Arrays.stream(body).filter(Objects::nonNull).toArray()`

**Review by williewillus — COMMENTED** [review]
see prior comment

**Comment by Tamaized** [comment]
Sure thing

File: src/main/java/twilightforest/entity/boss/EntityTFNaga.java (hunk 4 above)
Comment (Tamaized) [reply src/main/java/twilightforest/entity/boss/EntityTFNaga.java]: About this one, I wasn't exactly sure and spent a good while looking into it before, what i'm thinking is that the segments required data of the naga of somesort on the client side.. but tests made that untrue, and the code itself still doesnt quite make sense why this would work over the previous. I really coulnd't figure it out.

My other idea is that the naga itself on the client side needed its body array filled else it wouldnt show the segments, this one I suppose makes a bit more sense but still not sure to why exactly.

Comment (williewillus) [reply src/main/java/twilightforest/entity/boss/EntityTFNaga.java]: yea the multipart entity stuff is confusing. It's fine for now, can clean it up later

File: src/main/java/twilightforest/entity/boss/EntityTFNaga.java (hunk 5 above)
Comment (Tamaized) [reply src/main/java/twilightforest/entity/boss/EntityTFNaga.java]: So I actually have very little to no experience with Java 8 streams, and this and casting wont quite work, what would be the proper short way to get to this return as Entity[]?

Edit: Nvm, I figured it out :b

**Comment by Tamaized** [comment]
Cleanup done~

**Comment by williewillus** [comment]
Awesome thanks
