### PR TITLE
[Fix] Giant Tools no longer allow reach beyond for the tools themselves.

### LINKED ISSUE #1660: Giant tools increase placing/interacting range
### Forge Version

43.1.25

### Twilight Forest Version

4.2.1421

### Client Log

_No response_

### Crash Report (if applicable)

_No response_

### Steps to Reproduce

1. Put a Giant's Pickaxe or Giant's Sword in your main hand
2.1 Attempt to interact with a block that has a GUI (such as a crafting table) that is out of normal reach but in reach with the giant tool's boost
2.2 Alternatively, put a block in your offhand and try to place it somewhere out of normal reach but in giant reach

### What You Expected

In case 1, the block GUI would not open
In case 2, the block would not place

### What Happened Instead

In case 1, the GUI opens
In case 2, the block places

### Additional Details

This is more an issue with how Forge applies changes to reach than it is an issue with Twilight Forest

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

### PR DESCRIPTION
**Pull request by bconlon1**
This PR fixes issue #1660, somewhat, by making Giant Tools' reach not carry over to the player's offhand, meaning it won't apply to things like block placement. However, it does not fix the accessing GUI's part as that is mainhand behavior with the tool, so I personally view it as a nonissue/intentional, but I can implement an additional fix for that part if desired.

closes #1660

### CODE REVIEW

**Review by Tamaized — APPROVED** [review]

**Review by GizmoTheMoonPig — APPROVED** [review]
yeah baby

File: src/main/java/twilightforest/ASMHooks.java [hunk 1]
```diff
@@ -223,4 +231,64 @@ public static Component book(Component component, CompoundTag tag) {
...
 		} else return component;
 	}
+
+	/**
+	 * Injection Point:<br>
+	 * {@link net.minecraft.world.item.Item#getPlayerPOVHitResult(Level, Player, ClipContext.Fluid)}<br>
+	 * [BEFORE ARETURN]
+	 */
+	public static BlockHitResult reach(BlockHitResult o, Level level, Player player, ClipContext.Fluid fluidMode) {
+		/*InteractionHand hand = ToolAbilityListener.INTERACTION_HAND;
```
Comment (Tamaized) [inline src/main/java/twilightforest/ASMHooks.java]: This and below needs to be uncommented and addressed when you're ready.

**Review by Tamaized — CHANGES_REQUESTED** [review]

**Review by Tamaized — APPROVED** [review]
