### PR TITLE
Fix #2029 trophy pedestals for creative players

### LINKED ISSUE #2029: You Are Unworthy
### NeoForge Version

20.4.200

### Twilight Forest Version

4.4.2271

### Client Log

_No response_

### Crash Report (if applicable)

_No response_

### Steps to Reproduce

Be in creative mode
Place Trophy Pedestal + Trophy
"You are unworthy"
Cry

### What You Expected

Expected the Trophy Pedestal to activate due to there being no restrictions on anything else while in creative (ie, breaking blocks in structures that are beyond a certain point in progression).

### What Happened Instead

I was simply not worthy. 

### Additional Details

image

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

### PR DESCRIPTION
**Pull request by Sleepy-Horse**
Make trophy pedestals work for players in creative (they are worthy now)

### CODE REVIEW

File: src/main/java/twilightforest/block/TrophyPedestalBlock.java [hunk 1]
```diff
@@ -126,7 +126,7 @@ private boolean areNearbyPlayersEligible(Level level, BlockPos pos) {
 	}
 
 	private boolean isPlayerEligible(Player player) {
-		return PlayerHelper.doesPlayerHaveRequiredAdvancements(player, TwilightForestMod.prefix("progress_lich"));
+		return PlayerHelper.doesPlayerHaveRequiredAdvancements(player, TwilightForestMod.prefix("progress_lich")) || player.getAbilities().instabuild;
```
Comment (Tamaized) [inline src/main/java/twilightforest/block/TrophyPedestalBlock.java:129]: Wouldn't Player#isCreative make more sense?

Comment (jodlodi) [reply src/main/java/twilightforest/block/TrophyPedestalBlock.java:129]: > Wouldn't Player#isCreative make more sense?

`player.getAbilities().instabuild` is not only consistent with vanilla, but its also the way we do it in most, if not all scenarios

Comment (Tamaized) [reply src/main/java/twilightforest/block/TrophyPedestalBlock.java:129]: I feel like that's a legacy thing that hasn't really been addressed by vanilla.

Comment (Sleepy-Horse) [reply src/main/java/twilightforest/block/TrophyPedestalBlock.java:129]: I placed player.getAbilities().instabuild because it is the ability to build. If there were a mod that added creative mode with health points (or any other game mode with instabuild = true), it would return true (and that makes sense to me).

Comment (Tamaized) [reply src/main/java/twilightforest/block/TrophyPedestalBlock.java:129]: Makes sense to me.

**Review by Tamaized — APPROVED** [review]

**Comment by AriaElidove** [comment]
Thank you Sleepy o7
